version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
      - cd chime-in-be
  pre_build:
    commands:
      - pnpm install
  build:
    commands:
      - pnpm build

artifacts:
  files:
    - '**/*'
